# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/igorbeduin/IDJ/IDJ-2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/igorbeduin/IDJ/IDJ-2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igorbeduin/IDJ/IDJ-2019/CMakeFiles /home/igorbeduin/IDJ/IDJ-2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igorbeduin/IDJ/IDJ-2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IDJ.o

# Build rule for target.
IDJ.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IDJ.o
.PHONY : IDJ.o

# fast build rule for target.
IDJ.o/fast:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/build
.PHONY : IDJ.o/fast

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Music.o: src/Music.cpp.o

.PHONY : src/Music.o

# target to build an object file
src/Music.cpp.o:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Music.cpp.o
.PHONY : src/Music.cpp.o

src/Music.i: src/Music.cpp.i

.PHONY : src/Music.i

# target to preprocess a source file
src/Music.cpp.i:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Music.cpp.i
.PHONY : src/Music.cpp.i

src/Music.s: src/Music.cpp.s

.PHONY : src/Music.s

# target to generate assembly for a file
src/Music.cpp.s:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Music.cpp.s
.PHONY : src/Music.cpp.s

src/Sprite.o: src/Sprite.cpp.o

.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i

.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s

.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/State.o: src/State.cpp.o

.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i

.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s

.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) -f CMakeFiles/IDJ.o.dir/build.make CMakeFiles/IDJ.o.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IDJ.o"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Music.o"
	@echo "... src/Music.i"
	@echo "... src/Music.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

